### PR TITLE
Color scheme tighten

### PR DESCRIPTION
**Pull request by curran**
Making a few requested color scheme changes.

### CODE REVIEW

**Comment by curran** [comment]
@seemantk Ready for review.

**Comment by curran** [comment]
image

**Comment by seemantk** [comment]
@curran, the colors look great.  Nice catch on matching the Party->Party gray.

Two things to chat about on the call: Matching Funds color seems off pallette, and should the purple "$0" be the same color as "None", thus moving the entire purple range down by one?

**Comment by curran** [comment]
@seemantk Good points.

Buried in the emails, I just uncovered this quote from Michael "Use dark purple for $0 and progressively lighter shades going up for the next four steps. $0 needs to be portrayed as part of the gradient.".

The colors for the matching were specified by Ronda, I believe she used the tool [coolors](https://coolors.co/), so she would be key to a discussion on the off-palette issue.

**Pull request merged**
