### PR TITLE
Footer

### LINKED ISSUE #271: Add footer
Similar to that found at http://www.cfinst.org/

### PR DESCRIPTION
**Pull request by curran**
Closes #271 
image

### CODE REVIEW

**Comment by curran** [comment]
I put this footer together based on the conversation with the CFI folks, where they want to be able to configure the content, but realized that we may want to revisit https://github.com/cfinst/cfinst.github.io/pull/260 and think about adding collaborator attribution and a link back to the GitHub repo here. At least we can put those in the initial footer as suggested content, and give full control to CFI thereafter. @seemantk Any thoughts on this? What would you like to see in the footer?

**Comment by curran** [comment]
Ok, here's what I've got so far:

image

Zoomed:

image

**Comment by curran** [comment]
Here's a variation with a darker background for CFI logo:

image

**Comment by curran** [comment]
@bglavin @seemantk Here's what we've got so far as a straw man for the footer. Totally open to suggestions on changes.

**Comment by seemantk** [comment]
@curran, this looks great!

Perhaps our names in alphabetical order to be consistent? :)

**Comment by curran** [comment]
@seemantk Sure, happy to reorder. Thanks for the feedback!

**Pull request merged**
