### PR TITLE
Format legend items using commas

### LINKED ISSUE #153: Format legend items using commas
Minor thing, but something that I think we can address fairly easily.

image

We're using a comma in "$10,000 or Greater", but not in the intervals, like "$2501 - $5000".

It would be great to unify these, and see things like "$2,501 - $5,000" with the commas.

### PR DESCRIPTION
**Pull request by curran**
Closes #153

### CODE REVIEW

**Comment by seemantk** [comment]
@curran, I just wanted to be sure I understand the changeset here.

Tthe use of comma as a thousands separator is only a convention for part of the world.  As such, d3.format(",") only does that in the appropriate locales (eg en_US, en_UK, and so on), but it will put a "." in others, and it will put separators in non-thousands spots in still others (think Indian lakhs & crores for example).

So, I agree with using d3.format for the numbers in the legend labels. However, in other locales, that could leave the hardcoded labels inconsistent with the programmatically formatted ones.

**Comment by curran** [comment]
@seemantk Ahh yes, good point. Probably we want to *always* use the en_US locale for the comma placement, no matter from where folks are viewing. I wonder if there's a way to do that?

**Comment by curran** [comment]
Alternatively we can just specify the labels manually in the YML, that would totally work too, having no risk of inconsistencies.

**Comment by curran** [comment]
It looks like we could use d3.formatLocale(definition) here https://github.com/d3/d3-format#formatLocale

**Comment by curran** [comment]
@seemantk Just pushed a commit where en_us is always used.

**Pull request merged**
